# core/recommender.py

import os
import google.generativeai as genai
from dotenv import load_dotenv
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# --- Test Section ---
# To allow this file to be tested independently, we import the search function
from core.search_engine import find_similar_products

# Load API key from .env file
load_dotenv()
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise ValueError("Google API key not found. Please add it to the .env file.")

genai.configure(api_key=GOOGLE_API_KEY)

# Select Gemini model
model = genai.GenerativeModel("gemini-1.5-flash")


def generate_recommendation(skin_profile: dict, product_list: list) -> str:
    """
    Generate a smart, personalized skincare recommendation using Gemini.

    Args:
        skin_profile (dict): The analyzed skin profile of the user.
        product_list (list): List of products retrieved from semantic search.

    Returns:
        str: Final recommendation text generated by Gemini.
    """

    # Prompt Engineering: define model role, context, data, and task
    prompt = f"""
    **Your Role:** You are an expert, friendly, and professional skincare advisor. Your advice must be accurate, safe, and helpful.

    **Context:** A user has provided a photo, and our vision system has analyzed their skin. Here is their skin profile:
    - **Skin Type:** {skin_profile.get('skin_type', 'N/A')}
    - **Primary Concerns:**
        - Redness Level: {skin_profile.get('redness_level', 'N/A')}
        - Wrinkle Level: {skin_profile.get('wrinkle_level', 'N/A')}
    - **Skin Tone Description:** {skin_profile.get('skin_tone_description', 'N/A')}

    **Candidate Products:** Based on this profile, our semantic search engine has identified the following top products:
    ---
    """

    # Add product details to the prompt
    for i, product in enumerate(product_list, 1):
        prompt += f"""
    **Product {i}:**
    - **Name:** {product.get('english_name')}
    - **Description:** {product.get('english_description')}
    - **Meta Info:** {product.get('english_meta_description')}
    ---
    """

    # Define task for the model
    prompt += """
    **Your Task:**
    1. Analyze the user's skin profile and the candidate products provided.
    2. Select the **single BEST product** from the list that most effectively addresses the user's primary concerns. If two products are equally good for different reasons, you may recommend a second one as an alternative.
    3. Generate a personalized recommendation in **clear and simple English**.
    4. For the recommended product(s), include a short section titled: "Why is this product right for you?" In this section, explain how the product's features (e.g., ingredients or benefits) directly address the user's concerns (e.g., redness, wrinkles).
    5. Use a friendly, supportive tone. Format the output using Markdown (e.g., headings, bold text).
    """

    print("\nSending request to Gemini with prompt length:", len(prompt))

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Error communicating with Gemini API: {e}"


# --- Example usage for testing ---
if __name__ == '__main__':
    sample_skin_features = {
        "skin_tone_description": "light with pink undertones",
        "skin_type": "combination",
        "redness_level": "medium",
        "wrinkle_level": "slight wrinkles"
    }

    print("--- Step 1 & 2: Simulating skin profile and initial product search ---")

    initial_products = find_similar_products(sample_skin_features, top_k=3)

    print("\n--- Step 3: Sending data to Gemini for final recommendation ---")

    final_recommendation = generate_recommendation(sample_skin_features, initial_products)

    print("\n" + "=" * 50)
    print("✨ Final Recommendation from Your Smart Skincare Advisor ✨")
    print("=" * 50)
    print(final_recommendation)
